---
apiVersion: v1
kind: Service
metadata:
  name: event-handler
  namespace: zeebe-dmn-example
  labels:
    app: event-handler
spec:
  type: NodePort
  selector:
    app: event-handler
  ports:
    - protocol: TCP
      port: 8080
      name: http
---
kind: Service
apiVersion: v1
metadata:
  name: event-handler-expose
  namespace: zeebe-dmn-example
spec:
  ports:
    - name: monitor
      protocol: TCP
      port: 81
      targetPort: 8080
  selector:
    app: zeebe
  type: LoadBalancer
  externalIPs:
    - {{your cluster public ip}}
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: event-handler
  namespace: zeebe-dmn-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: event-handler
    spec:
      containers:
        - name: event-handler
          image: nikolaypervukhin/event-handler
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: shared-settings