server:
  port: 8080

connection-zeebe-service:
  host: zeebe.t1c.dev.ts
  port: 80
  workers: 1
  enabled: true

zeebe-service:
  client:
    security:
      plaintext: true

process:
  name: test-messaging
