server:
  port: 8080

connection-zeebe-service:
  host: localhost
  port: 26500
  workers: 1
  enabled: true

zeebe-service:
  client:
    security:
      plaintext: true

process:
  name: test-gateway
